local K = require("mps-core.helpers")
local dap = require("dap")
local dapui = require("dapui")

-- Basic debugging keymaps, feel free to change to your liking!
K.map("n", "<F9>", dap.continue, { desc = "DAP: Start/Continue" })
K.map("n", "<F10>", dap.step_over, { desc = "DAP: Step Over" })
K.map("n", "<F11>", dap.step_into, { desc = "DAP: Step Into" })
K.map("n", "<F12>", dap.step_out, { desc = "DAP: Step Out" })
K.map("n", "<leader><F10>", dapui.toggle, { desc = "DAP: Toggle UI"})
K.map("n", "<Leader>dl", dap.run_last, { desc = "DAP: Run last" })
K.map("n", "<leader>b", dap.toggle_breakpoint, { desc = "DAP: Toggle Breakpoint" })
K.map("n", "<leader>B", function()
	local input = vim.fn.input("Breakpoint condition: ")
	dap.set_breakpoint(input)
end, { desc = "DAP: Set conditional Breakpoint" })
-- Toggle to see last session result. Without this, you can't see session output in case of unhandled exception.
K.map("n", "<Leader>Bl", function()
	local input = vim.fn.input("Log point message: ")
	require("dap").set_breakpoint(nil, nil, input)
end)
K.map("n", "<Leader>dr", function()
	require("dap").repl.open()
end)
-- K.map({ "n", "v" }, "<Leader>dh", function()
-- 	require("dap.ui.widgets").hover()
-- end)
-- K.map({ "n", "v" }, "<Leader>dp", function()
-- 	require("dap.ui.widgets").preview()
-- end)
-- K.map("n", "<Leader>df", function()
-- 	local widgets = require("dap.ui.widgets")
-- 	widgets.centered_float(widgets.frames)
-- end)
-- K.map("n", "<Leader>ds", function()
-- 	local widgets = require("dap.ui.widgets")
-- 	widgets.centered_float(widgets.scopes)
-- end)
