#!/bin/bash

usage() { echo "Usage: $0 [-x <value>] [-y <value>]" 1>&2; exit 1; }

while getopts ":x:y:" o; do
    case "${o}" in
        x)
            x=${OPTARG}
            ;;
        y)
            y=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${x}" ] || [ -z "${y}" ]; then
    usage
fi

echo "x = ${x}"
echo "y = ${y}"

