return {
    { "tpope/vim-fugitive" },
    { "tpope/vim-rhubarb" },
    { "tpope/vim-sleuth" },
    { "voldikss/vim-browser-search" },
    { "ellisonleao/gruvbox.nvim" },
    { "folke/tokyonight.nvim" },
    { "theprimeagen/harpoon" },
    { "mbbill/undotree" },
    { "tpope/vim-fugitive" },
    { "nvim-lua/plenary.nvim" },
    { "RRethy/vim-illuminate" },
    { "preservim/nerdtree" },
    { "akinsho/toggleterm.nvim",       version = "*",         config = true },
    { "nvim-tree/nvim-web-devicons" },
    { "ryanoasis/vim-devicons" },
    { "kyazdani42/nvim-tree.lua" },
    { "goolord/alpha-nvim" },
    { "saadparwaiz1/cmp_luasnip" },
    { "neovim/nvim-lspconfig" },
    { "hrsh7th/cmp-nvim-lsp" },
    { "hrsh7th/cmp-buffer" },
    { "hrsh7th/cmp-path" },
    { "hrsh7th/cmp-cmdline" },
    { "hrsh7th/nvim-cmp" },
    { "mg979/vim-visual-multi" },
    { "folke/tokyonight.nvim" },
    { "folke/which-key.nvim",          opts = {} },
    { "sakhnik/nvim-gdb" },
    { "airblade/vim-gitgutter" },
    { "vim-airline/vim-airline" },
    { "vim-airline/vim-airline-themes" },
    { "nvim-lualine/lualine.nvim" },
    { "windwp/nvim-autopairs",         event = "InsertEnter", },
}
