-- vim.api.nvim_create_autocmd(
-- 	{ "BufEnter" },
-- 	{ pattern = "*",
-- 		command =
-- 		"if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif" }
-- )
